# Generated by Django 5.1.7 on 2025-04-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancyreview',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='vacancyreview',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.vacancy'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
